version: "3"

services:
  talkootunkki:
    build: .
    container_name: talkootunkki
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TG_BOT_API_TOKEN: ${TG_BOT_API_TOKEN}
      WS_EVENT_BROADCAST_INTERVAL: ${WS_EVENT_BROADCAST_INTERVAL}
      PORT: ${BACKEND_PORT}
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: talkootunkki_postgres
    restart: always
    environment:
      POSTGRES_DB: talkoot
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

  nginx:
    image: nginx:mainline-alpine
    container_name: talkootunkki_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - talkootunkki
    networks:
      - app-network
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    container_name: talkootunkki_certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: >
      certonly
      --webroot
      --webroot-path=/var/www/html
      --agree-tos
      --email ${CERTBOT_EMAIL}
      --no-eff-email
      --staging
      -d talkoot.vuodenkyla.fi

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge