version: "3"

services:
  nginx:
    image: nginx:mainline-alpine
    container_name: setup_nginx
    restart: always
    volumes:
      - ./nginx/nginx.setup.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    ports:
      - 80:80

  certbot:
    image: certbot/certbot
    container_name: setup_certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: >
      certonly
        --webroot
        --webroot-path=/var/www/html
        --agree-tos
        --email ${CERTBOT_EMAIL}
        --no-eff-email
        -d talkoot.kampusjaosto.fi

volumes:
  certbot-etc:
  certbot-var:
  web-root: