version: "3"

services:
  talkootunkki:
    build: .
    container_name: talkootunkki
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TG_BOT_API_TOKEN: ${TG_BOT_API_TOKEN}
      WS_EVENT_BROADCAST_INTERVAL: ${WS_EVENT_BROADCAST_INTERVAL}
      PORT: ${BACKEND_PORT}
    ports:
      - 80:3001

  postgres:
    image: postgres:15-alpine
    container_name: talkootunkki_postgres
    restart: always
    environment:
      POSTGRES_DB: talkoot
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  # nginx:
  #   image: nginx
  #   container_name: talkootunkki_nginx
  #   restart: always
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #   depends_on:
  #     - talkootunkki
  #   ports:
  #     - 80:80

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - webserver
  #   command: >
  #     certonly
  #     --webroot
  #     --webroot-path=/var/www/html
  #     --agree-tos
  #     --no-eff-email
  #     --staging
  #     -d your_domain
  #     -d www.your_domain

# volumes:
#   certbot-etc:
#   certbot-var:
  # web-root:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/sammy/node_project/views/
  #     o: bind