import React from "react"
import NoSSR from './NoSSR'
import './twa.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function TwaLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <NoSSR>
      <div className="flex min-h-screen flex-col items-center overflow-x-hidden">
        { children }
      </div>
    </NoSSR>
  )
}


